"""
Django settings for spin_identity project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5^@b+7%p-cmdjazo5h1@)ld!d!p4_=czm@0+3jmh(*&!8x7$g5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', '0').lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'storages',
    'accounts',
    'api',
    'audit',
    'base',
    'notifications',
    'organizations',
    'permissions',
    'sso',
    'systems',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'spin_identity.healthz.HealthCheckMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api.middleware.gateway.GatewayControlMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'spin_identity.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spin_identity.wsgi.application'

CORS_ALLOWED_ORIGINS = [
    'https://stage-accounts.spinmobile.co',
    'https://stage-onboarding.spinmobile.co',
    'https://stage-v3-ui.spinmobile.co',
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    'X-SSO-Session-Id',
]

IDENTITY_DEFAULT_REDIRECT_PATHS = [
    path.strip()
    for path in os.environ.get('IDENTITY_DEFAULT_REDIRECT_PATHS', '/auth/callback').split(',')
    if path.strip()
]
IDENTITY_DEFAULT_LOGOUT_PATHS = [
    path.strip()
    for path in os.environ.get('IDENTITY_DEFAULT_LOGOUT_PATHS', '/auth/logout').split(',')
    if path.strip()
]

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_DB'),
        'USER': os.environ.get('DATABASE_USER'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD'),
        'HOST': os.environ.get('DATABASE_HOST'),
        'PORT': os.environ.get('DATABASE_PORT'),
        'OPTIONS': {
            'application_name': 'taswira-api',
            'connect_timeout': 10,
            'options': (
                '-c statement_timeout=300000 '
                '-c lock_timeout=75000 '
                '-c idle_in_transaction_session_timeout=60000 '
                '-c work_mem=32MB'
            ),  # 5 minute query timeout, 75 second lock timeout, 1 minute idle in transaction timeout, 32MB work memory per query
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

APP_PATH = os.environ.get('APP_PATH') or '/var/www/idms'
STATIC_URL = '/static/'
STATIC_ROOT = APP_PATH + '/static'
STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'
AUTHENTICATION_BACKENDS = [
    'accounts.auth_backends.RealmModelBackend',
]
SILENCED_SYSTEM_CHECKS = ['auth.W004']

AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')

AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', '')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', '')

_DEFAULT_STORAGE_BACKEND = (
    'storages.backends.s3boto3.S3Boto3Storage'
    if AWS_STORAGE_BUCKET_NAME
    else 'django.core.files.storage.FileSystemStorage'
)

STORAGES = {
    'default': {
        'BACKEND': _DEFAULT_STORAGE_BACKEND,
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

AWS_QUERYSTRING_AUTH = False
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None

AWS_S3_SIGNATURE_VERSION = 's3v4'

# Logging
_VALID_LOG_LEVELS = {'CRITICAL', 'ERROR', 'WARNING', 'INFO', 'DEBUG', 'NOTSET'}
_LOG_LEVEL_RAW = os.environ.get('LOG_LEVEL', 'INFO').upper()
LOG_LEVEL = _LOG_LEVEL_RAW if _LOG_LEVEL_RAW in _VALID_LOG_LEVELS else 'INFO'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {'level': LOG_LEVEL},
        'django.request': {'level': 'WARNING'},
        'accounts': {'level': LOG_LEVEL},
        'api': {'level': LOG_LEVEL},
        'audit': {'level': LOG_LEVEL},
        'base': {'level': LOG_LEVEL},
        'notifications': {'level': LOG_LEVEL},
        'organizations': {'level': LOG_LEVEL},
        'permissions': {'level': LOG_LEVEL},
        'sso': {'level': LOG_LEVEL},
        'systems': {'level': LOG_LEVEL},
    },
}

NOTIFY_BASE_URL = 'https://stage-notify.spinmobile.co'
NOTIFY_API_KEY = 'cc8bP6j7ChpyEet2MHUACqDuPDTZkph42MwU3JJTYjAOVVncK-x6IA'

# SSO settings
SSO_ISSUER = 'https://stage-identity.spinmobile.co'
SSO_PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCZ92y9reITAoeI
9suk4SIzpLaGnAdwH9t69ZvqY8LXUnU+zcoTVcy/iPlyCZWaWy7F5fhNXnYchEn+
cwt4UQ6VmkZXhGdc712OliqB9P13lmCdxa9r18OAF9nMlMD1se375JwDBj1ZTziV
o0ndpucrNBOU4TASy/7mdBp/Rwfw3QcpJv9ceTc5JOSDepad4L3wNBzxPDBG60gX
RC+0sRpLOVutBMThIf1KehMZS4yr3J0vSDUBgnmSLJRrd2DBE4JNklGeLusAGn0W
VcRtVKg7r/+h8owIFqJLaAGJZsB5pvQJ8SC+uz2QvqF6/I3Mdy8rUYidheCKhiOr
i/EjkJY9AgMBAAECggEACgGb0lcA7JnbO6JIeWJ9UcxoZWayEA4t+jeIpsrNgKd2
AbsnoSqQGDmbdpcbXzECYO+xe7vCItfRJEWPTwY7k6r3W9w5yH8w/iGRySjmKTW/
eTl+DVz0Mni6WbKoOL+T1y1UG1k2Nv3wUD9Qv2RHvVXQ2PnqoSobWphcmX2BDV0C
LNtWzzcPq2g9BlYWZ8SVXANeNJTKn/bde/RENUB2GLxCHGm/Ct2NDy0Aa47QizI6
FwvfNkYKsZHTiFAKHz4c6PBNDutJdnhIzukx5xTdQyx1qYofH1/uG2xj7kKE8Ddl
3oO+RzmyGOiOg/EqK1PE81eIJfk/67RWxCN+TRC8mQKBgQDTg4afVg4QiDcZme0B
rtI3t66Z5A3zxcE/MKJbK/2Dt8rX7DB4964Hh1IUTl9p0wEorDJDYuUtSqOji/U9
wMWpQHCHn29uBnAOeb755eZX92ElHfjQbITLBHjNGFMMfkHNxKviuBq3RsasQYNd
94adLgtnQuyrMk5bRZI2e+eNJQKBgQC6WWXp2z3DoDXY0m+mdoSTraqg2fEVKnL1
qc5u2eR6LgOc8RY0Kfgxw1U31+A23HowWignrMD40VLAJmmK+uFs3DG7YGHK2vAA
VpjgPXyB8N6iIzhlpLuCaxo351m+L4P6WsBGCWS3W6Ujdb9Sc9RhLYYcsgqlm4Tx
lhasTSu1OQKBgBy1/dAjHkWgN9qBymowENj/VfQNwNcWQOUS9PbrQb5fdGla5jmF
ZVogREP9X3Y97ipXNXtwMSu0tgG9PczkHfCbjqraOYX12cAdRo8lZd8K9WTUbLHe
CSiFsuAkLSHFAamsyKg91WKLeOxo+CwJLXyog2PA8d9LNNeu2eoLZ6MBAoGBAJbj
kFv9hFOExFUef/1f9hXGB2VbU5R53MACkP69O/2aiJ5psDroyOkyayxehlSlzeKc
/eqyPUa7569i6w73+dQ1r6czcbvZ73+2nu7jmo90xDCxKBdVfecqZf5iPA59VvY+
yXVsYbr+YAcIbrSKyasuO2u81lYmSU185Dr7+aoxAoGBAJjYLKUmYhNLXiL4pV1/
/CMLjJNXfhERjGX3Ql5qAJeWD8sucY+VPfcI3K1skPY64d+LZEjSRycS9zlrWwH/
87E53UldJq709ffrGOZ4DDFFjw61oUyfpxRrd4aqP6EdArhtbmTi6fdZrfQDdOSQ
+1cw/+dZRJ7QJyePA1AIcnc8
-----END PRIVATE KEY-----"""
SSO_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmfdsva3iEwKHiPbLpOEi
M6S2hpwHcB/bevWb6mPC11J1Ps3KE1XMv4j5cgmVmlsuxeX4TV52HIRJ/nMLeFEO
lZpGV4RnXO9djpYqgfT9d5ZgncWva9fDgBfZzJTA9bHt++ScAwY9WU84laNJ3abn
KzQTlOEwEsv+5nQaf0cH8N0HKSb/XHk3OSTkg3qWneC98DQc8TwwRutIF0QvtLEa
SzlbrQTE4SH9SnoTGUuMq9ydL0g1AYJ5kiyUa3dgwROCTZJRni7rABp9FlXEbVSo
O6//ofKMCBaiS2gBiWbAeab0CfEgvrs9kL6hevyNzHcvK1GInYXgioYjq4vxI5CW
PQIDAQAB
-----END PUBLIC KEY-----"""
