# Generated by Django 6.0.3 on 2026-04-23 08:41

import audit.mixins
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('user_id', 'Per User ID'), ('system_user_id', 'Per System User ID'), ('ip', 'Per IP'), ('endpoint', 'Per Endpoint'), ('user_id_endpoint', 'Per User ID + Endpoint'), ('system_user_id_endpoint', 'Per System User ID + Endpoint'), ('ip_endpoint', 'Per IP + Endpoint')], max_length=50)),
                ('limit', models.PositiveIntegerField(help_text='Number of requests allowed')),
                ('period', models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10)),
                ('period_count', models.PositiveIntegerField(default=1, help_text="Number of periods (e.g., 2 for '2 hours')")),
                ('endpoint_pattern', models.CharField(blank=True, help_text='Regex pattern for URL matching', max_length=200)),
                ('http_methods', models.CharField(blank=True, help_text='Comma-separated HTTP methods (GET,POST,etc)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are checked first')),
                ('block_duration_minutes', models.PositiveIntegerField(default=0, help_text='Block duration after limit exceeded (0 = no blocking)')),
            ],
            options={
                'db_table': 'api_ratelimit_rule',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RateLimitBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('blocked_until', models.DateTimeField(db_index=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ratelimitrule')),
            ],
            options={
                'db_table': 'api_ratelimit_block',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RateLimitAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('count', models.PositiveIntegerField(default=1)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ratelimitrule')),
            ],
            options={
                'db_table': 'api_ratelimit_attempt',
                'indexes': [models.Index(fields=['rule', 'key', 'window_start'], name='api_ratelim_rule_id_9639d9_idx'), models.Index(fields=['window_start'], name='api_ratelim_window__879e69_idx')],
                'unique_together': {('rule', 'key', 'endpoint', 'window_start')},
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
    ]
