# Generated by Django 6.0.3 on 2026-04-23 08:41

import audit.mixins
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('base', '0001_initial'),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=120)),
                ('logo_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='systems.system')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_organizations', to='accounts.systemuser')),
            ],
            options={
                'db_table': 'organizations_organization',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(blank=True, max_length=120)),
                ('tax_id', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_countries', to='base.country')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_countries', to='organizations.organization')),
            ],
            options={
                'db_table': 'organizations_organization_country',
                'unique_together': {('organization', 'country')},
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='organization',
            name='countries',
            field=models.ManyToManyField(related_name='organizations', through='organizations.OrganizationCountry', to='base.country'),
        ),
        migrations.CreateModel(
            name='OrganizationOnboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted — Awaiting Review'), ('documents_requested', 'Additional Documents Requested'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('onboarded', 'Onboarded')], db_index=True, default='draft', max_length=30)),
                ('legal_name', models.CharField(max_length=255)),
                ('trading_name', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=120)),
                ('tax_id', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('applicant_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_onboardings', to='accounts.systemuser')),
                ('contact_system_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_onboardings', to='accounts.systemuser')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboardings', to='base.country')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboardings', to='systems.system')),
            ],
            options={
                'db_table': 'organizations_onboarding',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='organization',
            name='onboarding',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organization', to='organizations.organizationonboarding'),
        ),
        migrations.CreateModel(
            name='OnboardingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('business_registration', 'Business Registration Certificate'), ('kra_pin', 'KRA PIN Certificate'), ('tax_compliance', 'Tax Compliance Certificate'), ('memorandum', 'Memorandum & Articles of Association'), ('director_id', 'Director National ID / Passport'), ('licence', 'Operating Licence'), ('other', 'Other')], max_length=40)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(upload_to='onboarding/documents/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='organizations.onboardingdocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to='accounts.systemuser')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to='accounts.systemuser')),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organizationonboarding')),
            ],
            options={
                'db_table': 'organizations_onboarding_document',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OnboardingActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('created', 'Application created'), ('updated', 'Application updated'), ('submitted', 'Application submitted'), ('document_uploaded', 'Document uploaded'), ('document_reviewed', 'Document reviewed'), ('document_requested', 'Additional document requested'), ('note_added', 'Note added'), ('assigned', 'Assigned to reviewer'), ('approved', 'Application approved'), ('rejected', 'Application rejected'), ('onboarded', 'Organisation onboarded')], db_index=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_activities', to='accounts.systemuser')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='organizations.onboardingdocument')),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='organizations.organizationonboarding')),
            ],
            options={
                'db_table': 'organizations_onboarding_activity',
                'ordering': ['-created_at'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('business_registration', 'Business Registration Certificate'), ('kra_pin', 'KRA PIN Certificate'), ('tax_compliance', 'Tax Compliance Certificate'), ('memorandum', 'Memorandum & Articles of Association'), ('director_id', 'Director National ID / Passport'), ('licence', 'Operating Licence'), ('other', 'Other')], max_length=40)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('reason', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_document_requests', to='accounts.systemuser')),
                ('fulfilled_by_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfils_request', to='organizations.onboardingdocument')),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='organizations.organizationonboarding')),
            ],
            options={
                'db_table': 'organizations_document_request',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON'), ('url', 'URL')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.systemuser')),
            ],
            options={
                'db_table': 'organizations_settings',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='base.country')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organizations.organization')),
            ],
            options={
                'db_table': 'organizations_branch',
                'unique_together': {('organization', 'country', 'code')},
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='organizationonboarding',
            index=models.Index(fields=['system', 'status'], name='organizatio_system__83eec9_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationonboarding',
            index=models.Index(fields=['contact_system_user'], name='organizatio_contact_29824c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationonboarding',
            index=models.Index(fields=['system', 'country', 'status'], name='organizatio_system__5de2ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationonboarding',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'submitted', 'documents_requested', 'under_review', 'approved'])), fields=('system', 'country', 'contact_system_user'), name='unique_active_onboarding_per_contact'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('system', 'slug')},
        ),
        migrations.AddIndex(
            model_name='onboardingdocument',
            index=models.Index(fields=['onboarding', 'document_type'], name='organizatio_onboard_300e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingdocument',
            index=models.Index(fields=['onboarding', 'status'], name='organizatio_onboard_665838_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingactivity',
            index=models.Index(fields=['onboarding', 'activity_type'], name='organizatio_onboard_696706_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingactivity',
            index=models.Index(fields=['onboarding', 'created_at'], name='organizatio_onboard_6cada2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['onboarding', 'fulfilled_at'], name='organizatio_onboard_832153_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationsettings',
            unique_together={('organization', 'key')},
        ),
    ]
