# Generated by Django 6.0.3 on 2026-04-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingactivity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Onboarding activities'},
        ),
        migrations.AlterModelOptions(
            name='organizationcountry',
            options={'verbose_name_plural': 'Organization countries'},
        ),
        migrations.AlterModelOptions(
            name='organizationsettings',
            options={'verbose_name_plural': 'Organization settings'},
        ),
    ]
