# Generated by Django 6.0.5 on 2026-06-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_onboarding_payments_services_verifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='accent_colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='organization',
            name='favicon_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='subdomain',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
