# Generated by Django 6.0.5 on 2026-06-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_branding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='onboardingpayment',
            new_name='organizatio_onboard_b608b8_idx',
            old_name='organizatio_onboard_9f4220_idx',
        ),
        migrations.RenameIndex(
            model_name='onboardingverificationrun',
            new_name='organizatio_onboard_ea5e6d_idx',
            old_name='organizatio_onboard_e7c73a_idx',
        ),
        migrations.RenameIndex(
            model_name='onboardingverificationrun',
            new_name='organizatio_onboard_b9c5e2_idx',
            old_name='organizatio_onboard_1e68c5_idx',
        ),
        migrations.AlterField(
            model_name='onboardingactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Application created'), ('updated', 'Application updated'), ('document_uploaded', 'Document uploaded'), ('document_reviewed', 'Document reviewed'), ('note_added', 'Note added'), ('assigned', 'Assigned to reviewer'), ('approved', 'Application approved'), ('rejected', 'Application rejected'), ('services_selected', 'Services selected'), ('payment_recorded', 'Payment recorded'), ('verification_triggered', 'Verification triggered'), ('verification_completed', 'Verification completed'), ('onboarded', 'Organisation onboarded')], db_index=True, max_length=40),
        ),
    ]
