# Generated by Django 6.0.5 on 2026-06-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_align_onboarding_migration_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subdomain',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
