# Generated by Django 6.0.3 on 2026-04-23 08:41

import audit.mixins
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('base', '0001_initial'),
        ('organizations', '0001_initial'),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_categories', to='systems.system')),
            ],
            options={
                'db_table': 'permissions_category',
                'unique_together': {('system', 'slug')},
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codename', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_read_only', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='systems.system')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions', to='permissions.permissioncategory')),
            ],
            options={
                'db_table': 'permissions_permission',
                'unique_together': {('system', 'codename')},
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('mfa_required', models.BooleanField(default=False)),
                ('mfa_allowed_methods', models.JSONField(blank=True, default=list)),
                ('mfa_reauth_window_minutes', models.PositiveSmallIntegerField(default=0, help_text='How recently MFA must have been verified (0 = any time in this session')),
                ('is_system_defined', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='base.country')),
                ('created_by_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_roles', to='organizations.organization')),
                ('parent_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='permissions.role')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='systems.system')),
            ],
            options={
                'db_table': 'permissions_role',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_permissions', to='accounts.user')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='permissions.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='permissions.role')),
            ],
            options={
                'db_table': 'permissions_role_permission',
                'unique_together': {('role', 'permission')},
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='permissions.RolePermission', to='permissions.permission'),
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effect', models.CharField(choices=[('grant', 'Grant'), ('deny', 'Deny')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_overrides', to='accounts.systemuser')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.permission')),
                ('system_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='accounts.systemuser')),
            ],
            options={
                'db_table': 'permissions_user_override',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['system', 'is_active'], name='permissions_system__59ac0e_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['system', 'country'], name='permissions_system__faee76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('system', 'country', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='userpermissionoverride',
            unique_together={('system_user', 'permission')},
        ),
    ]
