# Generated by Django 6.0.3 on 2026-04-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissioncategory',
            options={'verbose_name_plural': 'Permission categories'},
        ),
    ]
