# Generated by Django 6.0.3 on 2026-04-23 08:41

import audit.mixins
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'accounts_social_account',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('all_branches', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('removed', 'Removed')], db_index=True, default='pending', max_length=20)),
                ('provisioning_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('provisioning_phone', models.CharField(blank=True, db_index=True, max_length=30)),
                ('provisioning_national_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('claim_token_lookup_id', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('claim_token_hash', models.CharField(blank=True, max_length=255)),
                ('claim_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('middle_name', models.CharField(blank=True, max_length=120)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=20)),
                ('profile_photo_url', models.URLField(blank=True)),
                ('external_ref', models.CharField(blank=True, db_index=True, max_length=120)),
                ('suspended_reason', models.TextField(blank=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'accounts_system_user',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('pin', models.CharField(blank=True, max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts_user',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier_type', models.CharField(choices=[('email', 'Email Address'), ('phone', 'Phone Number'), ('username', 'Username'), ('national_id', 'National ID')], max_length=30)),
                ('value', models.CharField(max_length=255)),
                ('value_normalised', models.CharField(db_index=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('disassociated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('disassociation_reason', models.CharField(blank=True, choices=[('user_removed', 'User removed it'), ('carrier_recycle', 'Carrier number recycled'), ('expired', 'Identifier expired'), ('admin_removed', 'Admin removed it'), ('superseded', 'Replaced by newer identifier')], max_length=30)),
            ],
            options={
                'db_table': 'accounts_user_identifier',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
    ]
