# Generated by Django 6.0.3 on 2026-05-06 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('base', '0001_initial'),
        ('organizations', '0001_initial'),
        ('permissions', '0001_initial'),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='branch_access',
            field=models.ManyToManyField(blank=True, related_name='memberships', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_users', to='base.country'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='provisioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_system_provisions', to='accounts.systemuser'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_memberships', to='permissions.role'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_system_users', to='accounts.systemuser'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_users', to='systems.system'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='accounts.systemuser'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='accounts.systemuser'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('realm', 'email'), name='unique_user_email_per_realm'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('realm', 'phone_number'), name='unique_user_phone_per_realm'),
        ),
        migrations.AddIndex(
            model_name='contactverification',
            index=models.Index(fields=['contact_type', 'value_normalized', 'created_at'], name='accounts_co_contact_7e4863_idx'),
        ),
        migrations.AddIndex(
            model_name='contactverification',
            index=models.Index(fields=['is_verified', 'consumed_at', 'expires_at'], name='accounts_co_is_veri_b218fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'uid'), name='unique_social_provider_uid'),
        ),
        migrations.AddIndex(
            model_name='systemuser',
            index=models.Index(fields=['system', 'country', 'organization'], name='accounts_sy_system__729169_idx'),
        ),
        migrations.AddIndex(
            model_name='systemuser',
            index=models.Index(fields=['user', 'system', 'status'], name='accounts_sy_user_id_b90a0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='systemuser',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'system', 'organization'), name='unique_user_per_system_org'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['system', 'is_verified', 'is_rewarded'], name='accounts_re_system__940233_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'is_verified', 'is_rewarded'], name='accounts_re_referre_aa54c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('referrer', models.F('referred')), _negated=True), name='accounts_referral_no_self_referral'),
        ),
    ]
