# Generated by Django 6.0.3 on 2026-04-23 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('base', '0001_initial'),
        ('organizations', '0001_initial'),
        ('permissions', '0001_initial'),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='branch_access',
            field=models.ManyToManyField(blank=True, related_name='memberships', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_users', to='base.country'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='provisioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_system_provisions', to='accounts.systemuser'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_memberships', to='permissions.role'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_system_users', to='accounts.systemuser'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_users', to='systems.system'),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='base.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='realm',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='base.realm'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_users', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='useridentifier',
            name='added_by_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_identifiers', to='systems.system'),
        ),
        migrations.AddField(
            model_name='useridentifier',
            name='disassociated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disassociated_identifiers', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='useridentifier',
            name='realm',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='base.realm'),
        ),
        migrations.AddField(
            model_name='useridentifier',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='accounts.user'),
        ),
        migrations.AddIndex(
            model_name='systemuser',
            index=models.Index(fields=['system', 'country', 'organization'], name='accounts_sy_system__729169_idx'),
        ),
        migrations.AddIndex(
            model_name='systemuser',
            index=models.Index(fields=['user', 'system', 'status'], name='accounts_sy_user_id_b90a0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='systemuser',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'system', 'organization'), name='unique_user_per_system_org'),
        ),
        migrations.AddIndex(
            model_name='useridentifier',
            index=models.Index(fields=['realm', 'identifier_type', 'value_normalised'], name='accounts_us_realm_i_2e1fec_idx'),
        ),
        migrations.AddIndex(
            model_name='useridentifier',
            index=models.Index(fields=['user', 'identifier_type'], name='accounts_us_user_id_2dc7f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='useridentifier',
            constraint=models.UniqueConstraint(condition=models.Q(('disassociated_at__isnull', True)), fields=('realm', 'identifier_type', 'value_normalised'), name='unique_active_identifier_per_realm'),
        ),
    ]
