# Generated by Django 6.0.3 on 2026-04-23 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='base.realm'),
        ),
        migrations.AlterField(
            model_name='useridentifier',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='base.realm'),
        ),
    ]
