# Generated by Django 6.0.3 on 2026-04-24 07:37

import audit.mixins
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_realm_alter_useridentifier_realm'),
        ('systems', '0003_system_allows_referrals_system_auto_verify_referrals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_code', models.CharField(db_index=True, max_length=32)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_rewarded', models.BooleanField(default=False)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_record', to='accounts.systemuser')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='accounts.systemuser')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='systems.system')),
            ],
            options={
                'db_table': 'accounts_referral',
                'indexes': [models.Index(fields=['system', 'is_verified', 'is_rewarded'], name='accounts_re_system__940233_idx'), models.Index(fields=['referrer', 'is_verified', 'is_rewarded'], name='accounts_re_referre_aa54c9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('referrer', models.F('referred')), _negated=True), name='accounts_referral_no_self_referral')],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
    ]
