# Generated by Django 6.0.3 on 2026-04-23 08:41

import audit.mixins
import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.UUIDField(db_index=True, editable=False)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('system_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('sso_session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('token_jti', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('request_method', models.CharField(max_length=10)),
                ('request_path', models.TextField()),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('is_secure', models.BooleanField(default=False)),
                ('view_name', models.CharField(blank=True, max_length=255, null=True)),
                ('view_args', models.JSONField(blank=True, null=True)),
                ('view_kwargs', models.JSONField(blank=True, null=True)),
                ('exception_type', models.CharField(blank=True, max_length=255, null=True)),
                ('exception_message', models.TextField(blank=True, null=True)),
                ('exception_traceback', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.FloatField(blank=True, null=True)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_request_log',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('auth.login.success', 'Login Success'), ('auth.login.failed', 'Login Failed'), ('auth.login.locked', 'Login Locked'), ('auth.logout', 'Logout'), ('auth.logout.global', 'Logout Global'), ('auth.mfa.enrollment_initiated', 'Mfa Enrollment Initiated'), ('auth.mfa.enrolled', 'Mfa Enrolled'), ('auth.mfa.removed', 'Mfa Removed'), ('auth.mfa.verified', 'Mfa Verified'), ('auth.mfa.failed', 'Mfa Failed'), ('auth.mfa.required', 'Mfa Required'), ('auth.mfa.enrollment_required', 'Mfa Enrollment Required'), ('auth.mfa.enrollment_complete', 'Mfa Enrollment Complete'), ('auth.mfa.method_suspended', 'Mfa Method Suspended'), ('auth.mfa.primary_changed', 'Mfa Primary Changed'), ('auth.mfa.backup_codes_generated', 'Backup Codes Generated'), ('auth.password.changed', 'Password Changed'), ('auth.password.reset', 'Password Reset'), ('auth.magic_link.sent', 'Magic Link Sent'), ('auth.magic_link.used', 'Magic Link Used'), ('auth.passwordless.initiated', 'Passwordless Initiated'), ('auth.passwordless.verified', 'Passwordless Verified'), ('auth.session.created', 'Session Created'), ('auth.session.revoked', 'Session Revoked'), ('auth.session.reauth_required', 'Session Reauth Required'), ('auth.token.issued', 'Token Issued'), ('auth.token.refreshed', 'Token Refreshed'), ('auth.token.revoked', 'Token Revoked'), ('auth.token.refresh_reuse_detected', 'Token Refresh Reuse'), ('auth.context.selected', 'Context Selected'), ('identifier.added', 'Identifier Added'), ('identifier.verified', 'Identifier Verified'), ('identifier.promoted', 'Identifier Promoted'), ('identifier.disassociated', 'Identifier Disassociated'), ('identifier.recycled', 'Identifier Recycled'), ('user.created', 'User Created'), ('user.updated', 'User Updated'), ('user.deleted', 'User Deleted'), ('system_user.created', 'System User Created'), ('system_user.claimed', 'System User Claimed'), ('system_user.invited', 'System User Invited'), ('user.suspended', 'User Suspended'), ('user.restored', 'User Restored'), ('user.linked_to_system', 'User Linked To System'), ('org.created', 'Org Created'), ('org.updated', 'Org Updated'), ('org.deactivated', 'Org Deactivated'), ('org.reactivated', 'Org Reactivated'), ('org.settings.changed', 'Org Settings Changed'), ('org.settings.deleted', 'Org Setting Deleted'), ('org.country.added', 'Org Country Added'), ('org.country.updated', 'Org Country Updated'), ('org.country.deactivated', 'Org Country Deactivated'), ('org.member.added', 'Member Added'), ('org.member.removed', 'Member Removed'), ('org.member.suspended', 'Member Suspended'), ('org.member.unsuspended', 'Member Unsuspended'), ('org.member.role_changed', 'Member Role Changed'), ('org.member.branch_changed', 'Member Branch Changed'), ('org.branch.created', 'Branch Created'), ('org.branch.updated', 'Branch Updated'), ('org.branch.deactivated', 'Branch Deactivated'), ('org.branch.reactivated', 'Branch Reactivated'), ('role.created', 'Role Created'), ('role.updated', 'Role Updated'), ('role.deleted', 'Role Deleted'), ('permission.granted', 'Permission Granted'), ('permission.revoked', 'Permission Revoked'), ('permission.override.created', 'Override Created'), ('permission.override.revoked', 'Override Revoked'), ('system.created', 'System Created'), ('system.settings.changed', 'System Settings Changed'), ('system.webhook.triggered', 'Webhook Triggered'), ('system.webhook.failed', 'Webhook Failed')], db_index=True, max_length=80)),
                ('actor_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor_system_user_id', models.UUIDField(blank=True, null=True)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor_user_agent', models.TextField(blank=True)),
                ('subject_type', models.CharField(blank=True, max_length=60)),
                ('subject_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('subject_label', models.CharField(blank=True, max_length=255)),
                ('system_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('system_name', models.CharField(blank=True, max_length=120)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('sso_session_id', models.UUIDField(blank=True, null=True)),
                ('token_jti', models.UUIDField(blank=True, null=True)),
                ('identifier_type', models.CharField(blank=True, max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('partial', 'Partial')], default='success', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['actor_user_id', 'created_at'], name='audit_log_actor_u_745545_idx'), models.Index(fields=['event_type', 'created_at'], name='audit_log_event_t_e775dd_idx'), models.Index(fields=['system_id', 'created_at'], name='audit_log_system__0e718a_idx'), models.Index(fields=['organization_id', 'created_at'], name='audit_log_organiz_6594e3_idx'), models.Index(fields=['subject_id', 'created_at'], name='audit_log_subject_ff7e0e_idx'), models.Index(fields=['identifier_type', 'created_at'], name='audit_log_identif_648e0e_idx')],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ModelAuditConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('track_create', models.BooleanField(default=True)),
                ('track_update', models.BooleanField(default=True)),
                ('track_delete', models.BooleanField(default=True)),
                ('excluded_fields', models.JSONField(blank=True, default=list)),
                ('retention_days', models.PositiveIntegerField(default=365)),
            ],
            options={
                'db_table': 'audit_model_configuration',
                'unique_together': {('app_label', 'model_name')},
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ModelAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=10)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'model_audit_log',
                'indexes': [models.Index(fields=['created_at', 'event_type'], name='model_audit_created_875fdb_idx'), models.Index(fields=['content_type', 'object_id'], name='model_audit_content_9d5f5c_idx'), models.Index(fields=['severity', 'created_at'], name='model_audit_severit_ad6199_idx'), models.Index(fields=['user_id'], name='model_audit_user_id_146544_idx'), models.Index(fields=['request_id'], name='model_audit_request_e396aa_idx')],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
    ]
