# Generated by Django 6.0.5 on 2026-06-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelauditlog',
            name='activity_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='modelauditlog',
            name='request_method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='modelauditlog',
            name='request_path',
            field=models.TextField(blank=True),
        ),
    ]
