# Generated by Django 6.0.3 on 2026-05-06 07:52

import audit.mixins
import django.db.models.deletion
import secrets
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('password_type', models.CharField(choices=[('password', 'Password'), ('pin', 'PIN')], default='password', max_length=10)),
                ('allow_password_login', models.BooleanField(default=True)),
                ('allow_passwordless_login', models.BooleanField(default=False)),
                ('allow_magic_link_login', models.BooleanField(default=False)),
                ('allow_social_login', models.BooleanField(default=False)),
                ('passwordless_only', models.BooleanField(default=False)),
                ('allowed_social_providers', models.JSONField(default=list)),
                ('registration_open', models.BooleanField(default=True)),
                ('auto_login_after_registration', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('allows_referrals', models.BooleanField(default=False)),
                ('referral_reward_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('auto_verify_referrals', models.BooleanField(default=False)),
                ('mfa_required', models.BooleanField(default=False)),
                ('mfa_required_enforced', models.BooleanField(default=False)),
                ('allowed_mfa_methods', models.JSONField(default=list, help_text='Empty = all MFA methods permitted. Non-empty = restrict to listed methods.')),
                ('refresh_token_timeout_minutes', models.PositiveIntegerField(blank=True, help_text='If set, users must re-login for this system once their refresh token has been unused for this many minutes — even with an active SSO session.  NULL = silent reauth.', null=True)),
                ('mfa_reauth_window_minutes', models.PositiveIntegerField(blank=True, help_text='MFA must be re-verified for this system if no token refresh has occurred within this window.  0 = disabled.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('available_countries', models.ManyToManyField(related_name='available_systems', to='base.country')),
                ('realm', models.ForeignKey(help_text='Realm determines SSO boundary and identifier uniqueness', on_delete=django.db.models.deletion.PROTECT, related_name='systems', to='base.realm')),
            ],
            options={
                'db_table': 'systems_system',
                'ordering': ['name'],
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SystemWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('endpoint_url', models.URLField()),
                ('secret_encrypted', models.TextField()),
                ('event_types', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='systems.system')),
            ],
            options={
                'db_table': 'systems_webhook',
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SystemClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('client_id', models.CharField(default=secrets.token_urlsafe, max_length=80, unique=True)),
                ('client_secret_hash', models.CharField(blank=True, max_length=255)),
                ('client_type', models.CharField(choices=[('confidential', 'Confidential (server-side)'), ('public', 'Public (SPA / mobile)'), ('m2m', 'Machine-to-Machine')], default='confidential', max_length=30)),
                ('redirect_uris', models.JSONField(default=list)),
                ('logout_uris', models.JSONField(default=list)),
                ('allowed_scopes', models.JSONField(default=list)),
                ('access_token_ttl', models.PositiveIntegerField(default=0)),
                ('refresh_token_ttl', models.PositiveIntegerField(default=0)),
                ('id_token_ttl', models.PositiveIntegerField(default=0)),
                ('override_allow_passwordless_login', models.BooleanField(blank=True, null=True)),
                ('override_allow_magic_link_login', models.BooleanField(blank=True, null=True)),
                ('override_allow_social_login', models.BooleanField(blank=True, null=True)),
                ('override_allowed_social_providers', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='systems.system')),
            ],
            options={
                'db_table': 'systems_client',
                'unique_together': {('system', 'name')},
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='systems.system')),
            ],
            options={
                'verbose_name_plural': 'System settings',
                'db_table': 'systems_settings',
                'unique_together': {('system', 'key')},
            },
            bases=(audit.mixins.AuditableMixin, models.Model),
        ),
    ]
