# Generated by Django 6.0.3 on 2026-04-24 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name_plural': 'System settings'},
        ),
        migrations.AlterField(
            model_name='system',
            name='realm',
            field=models.ForeignKey(help_text='Realm determines SSO boundary and identifier uniqueness', on_delete=django.db.models.deletion.PROTECT, related_name='systems', to='base.realm'),
        ),
    ]
