# Generated by Django 6.0.3 on 2026-05-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='allowed_mfa_methods',
            field=models.JSONField(blank=True, default=list, help_text='Empty = all MFA methods permitted. Non-empty = restrict to listed methods.', null=True),
        ),
    ]
