# Generated by Django 6.0.3 on 2026-05-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_alter_system_allowed_mfa_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemclient',
            name='allowed_scopes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='systemclient',
            name='logout_uris',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='systemclient',
            name='redirect_uris',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
