# Generated by Django 6.0.3 on 2026-04-24 07:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_alter_systemsettings_options_alter_system_realm'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='allows_referrals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='system',
            name='auto_verify_referrals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='system',
            name='referral_reward_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
