# Generated by Django 6.0.3 on 2026-05-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        ('systems', '0003_alter_systemclient_allowed_scopes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='default_role',
            field=models.ForeignKey(blank=True, help_text='Default role for systems that allow self registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_role', to='permissions.role'),
        ),
    ]
