# Generated by Django 6.0.5 on 2026-06-02 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_system_default_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='accent_colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='system',
            name='parent_system',
            field=models.ForeignKey(blank=True, help_text='Parent system for reseller systems. Blank means this is a root system.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resellers', to='systems.system'),
        ),
        migrations.AddField(
            model_name='system',
            name='favicon_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='system',
            name='primary_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='system',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='system',
            name='subdomain',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='system',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
