# Generated by Django 6.0.5 on 2026-06-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_system_resellers_branding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='subdomain',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
